/*
VISUALIZAR LOS NOMBRES DE LOS CLIENTES Y LA CANTIDAD DE ENCARGOS REALIZADOS,
INCLUIYENDO LOS QUE NO HAYAN REALIZADO ENCARGOS
*/

INSERT INTO clientes VALUES (NULL, 5, 'Tienda Organica Inc', 'Murcia', 0, CURDATE());

SELECT c.nombre, COUNT(e.id) FROM clientes c
LEFT JOIN encargos e ON c.id = e.cliente_id
GROUP BY 1;