/*
VISUALIZAR EL NOMBRE Y LOS APELLIDOS DE LOS VENDEDORES EN UNA MISMA CLUMNA,
SU FECHA DE REGISTRO Y EL DIA DE LA SEMANA EN LA QUE SE REGISTRARON
*/

SELECT CONCAT(nombre, ' ', apellidos) AS 'Nombre y apellidos',
fecha, DAYNAME(fecha) FROM vendedores;