/*
MOSTRAR LOS DATOS DEL VENDEDOR CON MAS ANTIGUEDAD EN EL CONCESIONARIO
*/
SELECT * FROM vendedores ORDER BY fecha ASC LIMIT 1;

/*
30 PLUS: OBTENER EL COCHES CON MAS UNIDADES VENDIDAS
*/
SELECT * FROM coches WHERE id IN
    (SELECT coche_id FROM encargos WHERE cantidad IN 
        (SELECT MAX(cantidad) FROM encargos));