/*
VISUALIZAR LOS APELLIDOS DE LOS VENDEDORES, SU FECHA Y SU NUMERO DE GRUPO ,
ORDENADO POR FECHA DESCENDENTE Y LIMITAR O MOSTRAR LOS 4 ULTIMOS
*/
SELECT apellidos, id FROM vendedores
ORDER BY fecha DESC LIMIT 4;
